### ISSUE TITLE
Problem with Cross-Registration

### ISSUE THREAD

**Issue by ForoughHa** [denisecailab/minian#52]
I am working with long recording sessions (more than 25 files with 1000 frames) and I have found that minian cannot process them all in one chunk as I face memory errors even when allocating 1.5TB of RAM to the process.
So I have now broken down my session to 3 chunks and have successfully run the pipeline on all and I need to cross-register them now. But unfortunately, I cannot get this notebook to work (I have tried both master and dev branches). The current script on the master branch seems to be functioning with less errors however I still get this error:

<img width="1434" alt="Screen Shot 2020-05-06 at 3 42 43 pm" src="https://user-images.githubusercontent.com/34736867/81141532-4aca2800-8fb0-11ea-9c92-413db804519d.png">
<img width="1397" alt="Screen Shot 2020-05-06 at 3 42 49 pm" src="https://user-images.githubusercontent.com/34736867/81141535-4f8edc00-8fb0-11ea-8e1e-16310db0a181.png">

My own guess is that the problem comes from when I am opening the datasets:

<img width="1427" alt="Screen Shot 2020-05-06 at 3 44 03 pm" src="https://user-images.githubusercontent.com/34736867/81141568-70573180-8fb0-11ea-898e-44bcb930049c.png">

As you can see, I am opening 3 separate folders of data but apparently, only the last folder has been stored in __minian_ds__. 
I don't set any of the data dimensions manually when I run minian on my videos; Could the problem be because of the naming of the sessions or other data dimensions? 
Am I missing something here? Has anyone been able to successfully do a cross-registration on different chunks of a long session?

**Comment by wmau** [comment]
Hi @ForoughHa ,

Can you open an issue regarding the memory error please? 

I have not worked much with the cross-registration portion of the pipeline. @phildong can you help?

**Comment by ForoughHa** [comment]
Hi @wmau,

Thank you very much for your reply. I will create a new issue in that regard.

**Comment by phildong** [comment]
yeah the issue is most likely due to the fact that `session` dimension has only size 1, and that in turn is because all your datasets has the same `session` label.
Those labels are controlled by `meta_dict` and you can find their usage under `pipeline_noted`. For a ad-hoc fix you can always manually open each dataset with `open_minian`, and use [`.assign_coords`](http://xarray.pydata.org/en/stable/generated/xarray.Dataset.assign_coords.html) on the dataset to change label, then use [`concat`](http://xarray.pydata.org/en/stable/generated/xarray.concat.html)

**Comment by ForoughHa** [comment]
Dear @phildong ,

Thank you very much for your reply. Yes, that was actually my mistake there. Though I will keep further experimenting with the cross-registration script on hold for now while I try to get the main pipeline working on the full recording sessions using @wmau's comments in the #53 issue thread. 
Hopefully, that would result more accurate processing of my data.

**Comment by ForoughHa** [comment]
Dear all,

I hope this email finds you well and safe.
As you might remember, I work on a project which requires me to use very
lengthy Miniscope recordings and I need these long recordings for an
accurate analysis. So far, I have been able to analyze video files of
maximum ~30 minutes long (50 .avi files from our Miniscope) using our
institution's HPC system which allows me a maximum of 2TB RAM allocation.
However, I actually need even longer recordings (approximately up to 1
hour) which unfortunately cannot be processed in a single batch using
Minian and with 2TB of RAM. I assume I will need much larger memory
allocations to be able to do that (to the best of my knowledge). Now, I was
thinking that clearly, performing a cross-registration step would be the
best option for me after I process different recording batches separately.
But unfortunately, I haven't been able to make the "Cross Registration"
script of minian to work no matter which branch (*master* or *dev*) I try,
there seems to be incompatibilities and issues including but certainly not
limited to my *meta_dict *structure.

I would now appreciate it if you could let me know of your suggestions for
me about how to proceed.

   - Would you suggest using the *dev* branch or is the *master* branch
   more reliable?
   - Is the "Cross Registration" script fully developed already and
   expected to work flawlessly on batches of data?
   - Would you please be able to provide a small hypothetical example of a
   meta_dict structure that should work with the Cross Registration code? (the
   field names and sample values for them given for example 2 batches of
   processed videos)
   - Finally, to change the labels of "sessions" or "animals" in different
   batches, I once tried to do that manually (by opening the file containing
   that information in all the output folders of minian and simply changing
   the text inside that file) but then I got a new set of errors from the
   script! Would you please let me know of the best way to do so that doesn't
   disrupt the whole pipeline?

Thank you very much in advance for your time.

Best Regards,

Forough Habibollahi | Ph.D. Candidate

Neural Dynamics Laboratory

Department of Biomedical Engineering, Melbourne Brain Center

The University of Melbourne

**Comment by wmau** [comment]
Hi Forough,

Unfortunately, we are currently experiencing some bugs with the cross registration due to some refactorings that are now causing errors. We are currently working on a fix but in the meantime, you may want to try another cross-registration platform. This one is Matlab based but is quite stable: https://github.com/zivlab/CellReg. You can try this code on my personal github repo to convert Minian outputs to CellReg-compatible inputs. In light of your message, we'll move this item high on the priority list and hopefully we address these bugs soon. Once we do, we'll let you know as soon as possible. 

Will

**Comment by ForoughHa** [comment]
Dear Will,

Thank you very much for your reply and for considering my bug report. I
appreciate it.
I will start working around the CellReg toolbox while eagerly waiting for
new updates from minian :)

Bests,
Forough

**Comment by wmau** [comment]
@ForoughHa If you pull from the dev branch, this should now be fixed.

**Comment by ForoughHa** [comment]
@wmau, Thanks for informing me.
I have had a bit of time working on the new cross-registration code on the dev branch since you informed me of the updates. Though, I am still facing problems that I assume are related to the data structures and my input files.

Here's how I have stored the different sessions that need to be cross-registered.
1 main folder --> inside there are 3 folders each corresponding to 1 of the sessions --> inside each folder there are 1) all the video files (msCAM files) of that session and 2) another folder named minian.1 (or similarly minian.2, minian.3 for the other 2 sessions) and inside this minian.1 folder, all the outputs of minian pipeline are stored. 
Overall, the output files of the 3 sessions that I am using have the same animal and session labels but the session_id differs among them. 
I thought using:
`f_pattern = r'minian\.[0-9]+$' `
`id_dims = ['session_id']`
 will help but seems like I am still getting something wrong.

Will you please be able to let me know if I need to arrange and store my data in some other way? Or do I need to manually open and re-write the animal or session labels to be different among the 3 sessions?
I would appreciate your help.

Bests,
Forough

**Comment by wmau** [comment]
Once you have finished running minian on a session, I recommend not changing any folder names since that will mess with the metadata. Instead, simply keep all the folders where they are and specify the first cell of the notebook to search for minian folders in the directory that encompasses all the data. For example, I have the following directory structure: 
~/Data/Mouse1/FirstDate/FirstSession/minian
~/Data/Mouse1/SecondDate/SecondSession/minian
etc.
Then in the first cell of the notebook I have: 
`minian_path = "."
dpath = r"~Data/Mouse1"
f_pattern = r'minian$' 
id_dims = ['animal','session']`
Then run everything as normal.

**Comment by ForoughHa** [comment]
Hi @wmau,

After rearranging my data files as you suggested, I now have:

~/CrossReg_movies/DanielData1/minian
~/CrossReg_movies/DanielData2/minian
~/CrossReg_movies/DanielData3/minian

and I choose:
`minian_path = "."`
`dpath = "./CrossReg_movies"`
`f_pattern = r'minian$'`
`id_dims = ['animal','session']`

As I mentioned before, the output files of the 3 sessions that I am using have the same animal and session labels but the session_id differs among them.

But unfortunately, I am still getting the following **value error**:

> opening dataset under /Users/fhabibollahi/minian/CrossReg_movies/DanielData1
> opening minian
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-12-810a24a5dde9> in <module>
> ----> 1 minian_ds = open_minian_mf(
>       2     dpath, id_dims, pattern=f_pattern, backend='zarr')
> 
> ~/minian/minian/utilities.py in open_minian_mf(dpath, index_dims, result_format, pattern, sub_dirs, exclude, **kwargs)
>     210             fname = flist[-1]
>     211             print("opening {}".format(fname))
> --> 212             minian = open_minian(nextdir, fname=fname, **kwargs)
>     213             key = tuple([np.array_str(minian[d].values) for d in index_dims])
>     214             minian_dict[key] = minian
> 
> ~/minian/minian/utilities.py in open_minian(dpath, fname, backend, chunks, post_process)
>     171             if isdir(pjoin(mpath, d))
>     172         ]
> --> 173         ds = xr.merge(dslist)
>     174 
>     175         if chunks == "auto":
> 
> ~/opt/anaconda3/envs/minian/lib/python3.8/site-packages/xarray/core/merge.py in merge(objects, compat, join, fill_value)
>     791         dict_like_objects.append(obj)
>     792 
> --> 793     merge_result = merge_core(dict_like_objects, compat, join, fill_value=fill_value)
>     794     merged = Dataset._construct_direct(**merge_result._asdict())
>     795     return merged
> 
> ~/opt/anaconda3/envs/minian/lib/python3.8/site-packages/xarray/core/merge.py in merge_core(objects, compat, join, priority_arg, explicit_coords, indexes, fill_value)
>     553 
>     554     prioritized = _get_priority_vars_and_indexes(aligned, priority_arg, compat=compat)
> --> 555     variables, out_indexes = merge_collected(collected, prioritized, compat=compat)
>     556     assert_unique_multiindex_level_names(variables)
>     557 
> 
> ~/opt/anaconda3/envs/minian/lib/python3.8/site-packages/xarray/core/merge.py in merge_collected(grouped, prioritized, compat)
>     226                 variables = [variable for variable, _ in elements_list]
>     227                 try:
> --> 228                     merged_vars[name] = unique_variable(name, variables, compat)
>     229                 except MergeError:
>     230                     if compat != "minimal":
> 
> ~/opt/anaconda3/envs/minian/lib/python3.8/site-packages/xarray/core/merge.py in unique_variable(name, variables, compat, equals)
>     127         # first check without comparing values i.e. no computes
>     128         for var in variables[1:]:
> --> 129             equals = getattr(out, compat)(var, equiv=lazy_array_equiv)
>     130             if equals is not True:
>     131                 break
> 
> ~/opt/anaconda3/envs/minian/lib/python3.8/site-packages/xarray/core/variable.py in no_conflicts(self, other, equiv)
>    1680         or both, contain NaN values.
>    1681         """
> -> 1682         return self.broadcast_equals(other, equiv=equiv)
>    1683 
>    1684     def quantile(self, q, dim=None, interpolation="linear", keep_attrs=None):
> 
> ~/opt/anaconda3/envs/minian/lib/python3.8/site-packages/xarray/core/variable.py in broadcast_equals(self, other, equiv)
>    1661         except (ValueError, AttributeError):
>    1662             return False
> -> 1663         return self.equals(other, equiv=equiv)
>    1664 
>    1665     def identical(self, other, equiv=duck_array_ops.array_equiv):
> 
> ~/opt/anaconda3/envs/minian/lib/python3.8/site-packages/xarray/core/variable.py in equals(self, other, equiv)
>    1645         try:
>    1646             return self.dims == other.dims and (
> -> 1647                 self._data is other._data or equiv(self.data, other.data)
>    1648             )
>    1649         except (TypeError, AttributeError):
> 
> ~/opt/anaconda3/envs/minian/lib/python3.8/site-packages/xarray/core/variable.py in data(self)
>     341             return self._data
>     342         else:
> --> 343             return self.values
>     344 
>     345     @data.setter
> 
> ~/opt/anaconda3/envs/minian/lib/python3.8/site-packages/xarray/core/variable.py in values(self)
>     449     def values(self):
>     450         """The variable's data as a numpy.ndarray"""
> --> 451         return _as_array_or_item(self._data)
>     452 
>     453     @values.setter
> 
> ~/opt/anaconda3/envs/minian/lib/python3.8/site-packages/xarray/core/variable.py in _as_array_or_item(data)
>     252     TODO: remove this (replace with np.asarray) once these issues are fixed
>     253     """
> --> 254     data = np.asarray(data)
>     255     if data.ndim == 0:
>     256         if data.dtype.kind == "M":
> 
> ~/opt/anaconda3/envs/minian/lib/python3.8/site-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
>      83 
>      84     """
> ---> 85     return array(a, dtype, copy=False, order=order)
>      86 
>      87 
> 
> ~/opt/anaconda3/envs/minian/lib/python3.8/site-packages/xarray/core/indexing.py in __array__(self, dtype)
>     555     def __array__(self, dtype=None):
>     556         array = as_indexable(self.array)
> --> 557         return np.asarray(array[self.key], dtype=None)
>     558 
>     559     def transpose(self, order):
> 
> ~/opt/anaconda3/envs/minian/lib/python3.8/site-packages/xarray/backends/zarr.py in __getitem__(self, key)
>      47         array = self.get_array()
>      48         if isinstance(key, indexing.BasicIndexer):
> ---> 49             return array[key.tuple]
>      50         elif isinstance(key, indexing.VectorizedIndexer):
>      51             return array.vindex[
> 
> ~/opt/anaconda3/envs/minian/lib/python3.8/site-packages/zarr/core.py in __getitem__(self, selection)
>     570 
>     571         fields, selection = pop_fields(selection)
> --> 572         return self.get_basic_selection(selection, fields=fields)
>     573 
>     574     def get_basic_selection(self, selection=Ellipsis, out=None, fields=None):
> 
> ~/opt/anaconda3/envs/minian/lib/python3.8/site-packages/zarr/core.py in get_basic_selection(self, selection, out, fields)
>     692         # handle zero-dimensional arrays
>     693         if self._shape == ():
> --> 694             return self._get_basic_selection_zd(selection=selection, out=out,
>     695                                                 fields=fields)
>     696         else:
> 
> ~/opt/anaconda3/envs/minian/lib/python3.8/site-packages/zarr/core.py in _get_basic_selection_zd(self, selection, out, fields)
>     718 
>     719         else:
> --> 720             chunk = self._decode_chunk(cdata)
>     721 
>     722         # handle fields
> 
> ~/opt/anaconda3/envs/minian/lib/python3.8/site-packages/zarr/core.py in _decode_chunk(self, cdata)
>    1750         # segfaults and other bad things happening
>    1751         if self._dtype != object:
> -> 1752             chunk = chunk.view(self._dtype)
>    1753         elif chunk.dtype != object:
>    1754             # If we end up here, someone must have hacked around with the filters.
> 
> **ValueError: When changing to a larger dtype, its size must be a divisor of the total size in bytes of the last axis of the array.**
> 


Would you mind commenting on this in case you have any ideas about where this error might be originating from?

Bests,
Forough

**Comment by phildong** [comment]
Both the memory performance of the pipeline, and the cross registration algorithm should be improved in latest release.
Feel free to re-open if the issue persists!

**Comment by ForoughHa** [comment]
Thank you very much for the updates.
I could never get the cross-registration algorithm working properly. But I
will do my best to have another go in the very near future and re-open if I
still face the issue.


Bests,
Forough
